### ISSUE TITLE
Add deep-link parameter to dispatcher

### ISSUE THREAD

**Issue by SwapnanilDhol** [SwapnanilDhol/IGStoryKit#6]
Add a `com.instagram.sharedSticker.contentURL` parameter to the pasteboard items.

**Comment by halpz** [comment]
does the content-url even work any more? i'm trying to figure out how to include an attribution link or a link sticker through the instagram-stories pasteboard

**Comment by SwapnanilDhol** [comment]
@halpz AFAIK, it's only available to certain developers such as Spotify. Can't find a link for it right now but I'm pretty sure that's the case.
