### ISSUE TITLE
Share multiple stickers

### ISSUE THREAD

**Issue by Mudasir441** [SwapnanilDhol/IGStoryKit#8]
How can we add more than one sticker?

**Comment by SwapnanilDhol** [comment]
You can copy a sticker after the main sticker has been sent to IGStory and then paste it on the same story. The developer document doesn't mention/allow multiple stickers to be sent in one dispatch, unfortunately. https://developers.facebook.com/docs/instagram/sharing-to-stories/

Closing this issue. Feel free to reopen if I've misunderstood your query. Have a great day!
